kind: Deployment
apiVersion: apps/v1

metadata:
  name: postgresql
  labels:
    app: postgresql

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: postgresql-vol
          persistentVolumeClaim:
            claimName: postgresql-vol
      containers:
        - resources:
            limits:
              cpu: "250m"
              ephemeral-storage: 1G
              memory: "256Mi"
            requests:
              cpu: "250m"
              ephemeral-storage: 1G
              memory: "128Mi"
          terminationMessagePath: /dev/termination-log
          name: postgresql
          env:
            - name: POSTGRES_DB
              value: software-lab
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgresql-vol
              mountPath: /var/lib/postgresql/data
          terminationMessagePolicy: File
          image: 'postgres:9.5.21'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600