apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker

spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: worker
          image: registry.gitlab.com/farzad-845/crypto-clothes:latest
          command: [ "./deployment/celery/run.sh" ]
          envFrom:
            - secretRef:
                name: prod-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: 1G
            requests:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: 1G
      imagePullSecrets:
        - name: gitlab-registry-credentials