# Generated by Django 3.1.5 on 2021-01-11 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_factor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='factor_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_owner', related_query_name='factor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(related_name='group_members', related_query_name='group', to=settings.AUTH_USER_MODEL),
        ),
    ]
