# Generated by Django 3.1.5 on 2021-01-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210111_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.BigIntegerField(default=0),
        ),
    ]
