# Generated by Django 3.2.10 on 2021-12-27 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210111_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(auto_created=uuid.UUID('de3328a9-0af2-41ad-bcf8-3df510db8896')),
        ),
    ]
